// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/puregreen-hero/CleanGreen.tsx": () => import("../components/mockups/puregreen-hero/CleanGreen.tsx"),
  "./components/mockups/puregreen-hero/LightBold.tsx": () => import("../components/mockups/puregreen-hero/LightBold.tsx"),
  "./components/mockups/puregreen-hero/WarmConcrete.tsx": () => import("../components/mockups/puregreen-hero/WarmConcrete.tsx")
};
